### ISSUE TITLE
Google chrome says this extension has malware

### ISSUE THREAD

**Issue by jeenuv** [miscalencu/Google-Chrome-Google-Bookmarks#10]
I noticed on my laptop that Chrome suddenly disabled this extension, with the detail that it contains malware. See the screenshot below.

**Comment by jeenuv** [comment]
![screenshot at 2017-01-23 20 27 58](https://cloud.githubusercontent.com/assets/92313/22221383/b704b9fc-e1aa-11e6-81be-59c7be6eb874.png)

**Comment by miscalencu** [comment]
Hi Jeenuv,

It is possible. I no longer own the online extension.

If you want the original one (with clean code) you can download it from https://github.com/miscalencu/Google-Chrome-Google-Bookmarks/tree/LiteBookmarks and load it using "Load unpacked extension" feature in Chrome.

Regards,
George

**Comment by jeenuv** [comment]
I'm a bit alarmed. Was it the case that you owned the extension before, and then sold/handed over to a third party? Or did this happen without your knowledge at all?!

I do want to keep using the extension. I was originally pointed to this Github repository from the extension page itself, which gave me (and possibly other users too) the impression that the extension is put up with the author's blessing.

**Comment by miscalencu** [comment]
I owned it and then sold it to another party. They should have remove all references to this repository. I wanted to send them a message to do this, but now the extension seems down anyway... probably they tried to inject some kind of advertising script and Google removed it.

**Comment by jeenuv** [comment]
> They should have remove all references to this repository

I'm sure that wasn't their primary concern. Anyway, this thread gives some clarification to anyone seeking what went on.

**Comment by Jamaulgayles** [comment]
https://github.com/miscalencu/Google-Chrome-Google-Bookmarks
