### ISSUE TITLE
Lite Bookmarks extension automatically disabled by Chrome

### ISSUE THREAD

**Issue by tonibony** [miscalencu/Google-Chrome-Google-Bookmarks#11]
The current version of Google Chrome (56.0.2924.87) automatically disabled "Lite Bookmarks" extension, claiming "This extension contains malware". Enabling it is not allowed. The extension page in Google Play is missing.

**Comment by miscalencu** [comment]
Hi,

Please see issue https://github.com/miscalencu/Google-Chrome-Google-Bookmarks/issues/10.

Regards,
George

**Comment by tonibony** [comment]
Sorry, I missed this. Thank you anyway!

Would you recommend switching to your new extension "Simple Google Bookmarks Sync" instead of using the original code of "Lite Bookmarks" extension?

**Comment by miscalencu** [comment]
If you want to use the old one, get the clean code from here. If not, use the new one to copy/sync your bookmarks. It's entirely up to you.
